### ISSUE TITLE
Plugin titles not showing for MuseScore Studio 4.4

### ISSUE THREAD

**Issue by mrhso** [mirabilos/mscore-plugins#2]
https://github.com/musescore/MuseScore/wiki/Updating-plugins-for-MuseScore-Studio-4.4

**Comment by mirabilos** [comment]
Ouch.

That’s quite the amount of incompatible changes there, even if the one with the titles is lessened somewhat. The sentence there…

> MuseScore's plugins/extensions framework is undergoing a big transition

… makes me think that there will be even *more* incompatible changes soon.

Now, I {d,w}on’t use mu͒4, for a variety of reasons I already stated often enough in various places, so the mu͒4 versions of the plugins are effectively unmaintained and only kept due to user contributions (and, incidentally, they were only **created** in the first place because Jojo contributed them).

As it seems I do have users, I’ll do my part but will have to rely on you for testing and issue reports; I hope that’s okay.
